yuitama_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :plans
  resources :plans do
	member do
	  get 'show_image'
	end
  end
  resources :comments
  post "/utinaantyu/login" => "utinaantyus#login"
  get "/utinaantyus/login" => "utinaantyus#login_form"
  get "/utinaantyus/logout" =>"utinaantyus#logout"
  get '/plans/:id/book' => 'plans#book'
  get '/users/:user_id/:plan_id/cansel' => 'plans#cansel'
  get 'accept_plan/planMylist'
  get 'accept_plan/planDetail'
  get 'accept_plan/planList'

  get 'plan_consul/consensus'

  get 'provide_plan/planInput'
  get 'provide_plan/regiComp'
  get 'provide_plan/myPlanList'

  resources :users
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get "/user/signup" => "users#new"
  post "users/create" => "users#create"
  get "users/:id/edit" => "users#edit"
  post "users/:id/update" => "users#update"

  get "users/:id/mypage" => "users#mypage"
  get "/user/login" => "users#loginuser"
  post "/user/login" => "users#loginpost"
  get "/user/logout" => "users#logoutuser"


  resources :utinaantyus
  root 'home#index'
  # ホーム画面
  get 'home/index'
  # プランホーム画面
  get 'home/planHome'
  # ホームからログイン画面
  get 'home/login'

  # 個人情報登録画面
  get 'personal_info/input'
  # 個人情報登録完了画面
  get 'personal_info/regiComp'
  # ウチナーンチュマイページ
  get 'personal_info/mypage'
  # ウチナーンチュプロフィール編集
  get 'personal_info/editProf'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yuitama_app/app/models/plan.rb
class Plan < ApplicationRecord
  validates :content, presence: true
  has_many :comments, dependent: :destroy
end

yuitama_app/app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :set_currentuser
  before_action :authenticate_user, only: [:new, :edit, :update]
  before_action :ensure_currect_user, only: [:edit, :update, :destroy]


  # GET /plans
  # GET /plans.json
  def index()
    @counter = 0
    searchword = params[:search]
    searchgenre = params[:selected_val]

    if searchword
      if searchgenre == "内容"
        @plans = Plan.where(["content LIKE ?", "%#{searchword}%"]) #コンテント用
      elsif searchgenre == "ハッシュタグ"
        @plans = Plan.where(["content LIKE ?", "%##{searchword}%"]) #ハッシュタグ用
      end
      render
    else
      @plans = Plan.all
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @comment = @plan.comments.new
    @comments = @plan.comments
  end

  def show_image
	@plan = Plan.find(params[:id])
	send_data @plan.image, :type => 'image/jpeg', :disposition => 'inline'
  end


  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
	image = plan_params[:image]
	plan = {}
  plan = plan_params
	plan[:creator_id] = session[:user_id]
	if image != nil
	  plan[:image] = image.read
	else
    plan[:image] = File.open("#{Rails.root.to_s}/app/assets/images/no_image.png","r").read
	end
    @plan = Plan.new(plan)
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    plan = {}
    plan = plan_params
    plan[:creator_id] = @plan.creator_id
    if plan[:image] == nil
      plan[:image] = File.open("#{Rails.root.to_s}/app/assets/images/no_image.png","r").read
    end

    respond_to do |format|
      if @plan.update(plan)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def book
      if @current_pub_user then
        @plan = Plan.find(params[:id])
        @user = User.find_by(id: @current_pub_user.id)
        @user.bookedplan_id = @plan.id
        @user.save
        redirect_to "/users/#{@user.id}/mypage"
      else
        flash[:notice] = "You should need logged in !!"
      end
    end

    def cansel
      if @current_pub_user then
        @plan = Plan.find(params[:plan_id])
        @user = User.find_by(id: @current_pub_user.id)
        @user.bookedplan_id = nil
        @user.save
        redirect_to "/users/#{@user.id}/mypage"
      else
        flash[:notice] = "You should need logged in !!"
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title, :content, :image, :scheduled_date)
    end

    def set_currentuser
      @currentuser = Utinaantyu.find_by(id: session[:user_id])
    end

    def authenticate_user
      if @currentuser == nil
        flash[:notice] = "ログインが必要です"
        redirect_to("/utinaantyus/login")
      end
    end

    def ensure_currect_user
      if @currentuser.id != @plan.creator_id
        flash[:notice] = "権限がありません"
        redirect_to("/plans")
      end
    end

end

yuitama_app/app/helpers/plans_helper.rb
module PlansHelper
end

yuitama_app/app/views/plans/_form.html.erb
    <div class="row">
      <div class="col-md-5 p-0">
        <div id="carousel1" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
              <%if params[:id]!=nil%>
            <div class="carousel-item active">
                  <%= image_tag show_image_plan_path(plan), class:"d-block img-fluid w-100"%>
              <!-- 写真に文字被せるなら以下のタグ内に記載 -->
              <div class="carousel-caption plan-content">
              </div>
            </div>
              <%end%>
              <%if params[:id]==nil%>
            <div class="carousel-item active">
              <%else%>
            <div class="carousel-item">
              <%end%>
              <%= image_tag "no_image.png", class:"d-block img-fluid w-100"%>
              <div class="carousel-caption plan-content">
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
          <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
        </div>
      </div>
      <!-- ここに写真右側の文字 -->
      <div class="align-self-center p-5 col-md-7">

        <%= form_with(model: plan, local: true, class:"form-horizontal") do |form| %>
          <div class="form-group">
            <%= form.label "画像", class:"control-label col-md-2 plan-content"%>
            <div class=" col-md-10">
              <%= form.file_field :image, id: :plan_image ,:class => "plan-content btn btn-default btn-file form-control"%>
            </div>
            <% if plan.errors.messages[:image].any? %>
            <span class="text-warning plan-content"><%= plan.errors.messages[:image][0] %></span>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label "計画日", class:"control-label col-md-2 plan-content" %>
            <div class="col-md-10">
              <div class="input-group datepicker col-md-12 plan-content">
                <%= form.text_field :scheduled_date, id: :plan_scheduled_date ,:class => "form-control"%>
                <span class="input-group-addon col-md-1 plan-content">
                  <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                </span>
              </div>
            </div>
            <% if plan.errors.messages[:scheduled_date].any? %>
            <span class="text-warning plan-content"><%= plan.errors.messages[:scheduled_date][0] %></span>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label "タイトル", class:"control-label col-md-2 plan-content" %>
            <div class=" col-md-10">
              <%= form.text_area :title, id: :plan_title , :class => "form-control plan-content"%>
            </div>
            <% if plan.errors.messages[:title].any? %>
            <span class="text-warning plan-content"><%= plan.errors.messages[:title][0] %></span>
            <% end %>
          </div>

          <div class="form-group">
            <%= form.label "プラン内容", class:"control-label col-md-2 plan-content" %>
            <div class=" col-md-10">
              <%= form.text_area :content, id: :plan_content, size:"50x20" ,:class => "form-control plan-content"%>
            </div>
            <% if plan.errors.messages[:content].any? %>
            <span class="text-warning plan-content"><%= plan.errors.messages[:content][0] %></span>
            <% end %>
          </div>

          <div class="actions">
            <div class="col-md-offset-2 col-md-10 pt-4">
              <%= form.submit class:"btn btn-primary btn-block plan-content"%>
            </div>
          </div>
      </div>


      </div>

<% end %>

yuitama_app/app/views/plans/_index.html.erb
      <div class="col-md-4 py-4">
        <div class="card ">
          <%= link_to image_tag(show_image_plan_path(index), class: "img-responsive card-img-top"), index %>
          <div class="card-body">
            <p class="card-title"><b>案内内容</b></p>
            <p class="card-text text-truncate"><%= index.title %></p>
          </div>
        </div>
      </div>

yuitama_app/app/views/plans/_show.html.erb
<!-- <div class="col-md-6 p-0">-->
<div class="row p-0 justify-content-md-center">
  <div class="col-md-8">
    <div class="card">

      <div class="card-header text-left">
        <h1 class="pt-1 plan-title"><strong><%=@plan.title%></strong></h1>
      </div>

      <div class="card-body p-5 ">
      <div id="carousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">

          <div class="carousel-item active">
            <%= image_tag show_image_plan_path(plan), class:"d-block img-fluid w-100 img-thumbnaill"%>
            <!-- 写真に文字被せるなら以下のタグ内に記載 -->
            <div class="carousel-caption">
            </div>
          </div>

        </div>
        <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
        <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
      </div>
      <!-- ここに写真下側の文字 -->
      <!--<div class="align-self-center p-5 col-md-6">-->


      <div class="pt-5">
        <%if plan.scheduled_date == nil%>
        <p class="pb-5 plan-content">予定日: 未定</p>
        <%else%>
        <% d=plan.scheduled_date %>
        <p class="pb-5 plan-content">予定日: <%=d.strftime("%Y年 %m/%d %H:%M")%></p>
        <%end%>
        <p class="plan-content"><%=@plan.content%></p>
      </div>
            <%if @current_pub_user != nil%>
            <%if @current_pub_user.bookedplan_id then%>
            <div class="text-right">
              <div style="color:#0000ff;"><p class="plan-content" >このプランはブックマーク済み</p>
                <%= link_to("ブックマークを解除","/users/#{@current_pub_user.id}/#{@plan.id}/cansel", style:"font-size:1.5vw;color:0000ff;")%>
              </div>
            </div>
                <%else%>
            <div class="text-right">
                <%= link_to("このプランをブックマーク","#{@plan.id}/book", style:"font-size:1.0vw;color:0000ff;")%>
            </div>
            <%end%>
            <%end%>
        <p class="text-right mt-2 plan-content">
          提案者: <%= link_to("#{Utinaantyu.find(plan.creator_id).name}", "/utinaantyus/#{Utinaantyu.find(plan.creator_id).id}" ) %>
        </p>
      </div>
      <div class="card-footer">
        <div class="row p-2">
          <div class="col-md-4">

            <%= link_to image_tag("plan_edit",class:"img-responsive"), edit_plan_path(@plan) %>
          </div>
          <div class="col-md-4">
            <%= link_to image_tag("plan_delete",class:"img-responsive"),@plan, method: :delete, data:{confirm: '本当に削除しますか？'} %>
          </div>
          <div class="col-md-4">
            <%= link_to image_tag("_plans",class:"img-responsive"), plans_path %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

yuitama_app/app/views/plans/book.html.erb
<%= content_for(:maincontent)  do %>

<h1>plans#book</h1>

    <%= @plan.id%>

    <%= @current_pub_user.name%>


    <%if @user.bookedplan_id then%>

        <% @plannum = @user.bookedplan_id%>
        <% @temp = Plan.find(@plannum)%>
        <%= @temp.content%>
        <%= link_to("mypage","/users/#{@user.id}/mypage")%>


        <%end%>

<%end%> 

yuitama_app/app/views/plans/cansel.html.erb
<h1>Users#cansel</h1>
<p>Find me in app/views/users/mypage.html.erb</p>


<%= content_for(:maincontent) do%>

    <h2>canseled!!!!</h2>
    <%= link_to("mypage","/users/#{@current_pub_user.id}/mypage")%>

<%end%>

yuitama_app/app/views/plans/edit.html.erb
<%= content_for(:maincontent)  do %>
<div class="container-fluid p-5">
  <%= render 'form', plan: @plan %>

  <%= link_to 'Show', @plan %> |
  <%= link_to 'Back', plans_path %>
</div>
<% end %>

yuitama_app/app/views/plans/index.html.erb
<%= content_for(:maincontent)  do %>
<p id="notice"><%= notice %></p>

<div class="container-fluid px-4">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag("plans.png", align:"left", class:"img-responsive ", size:"300x135") %>
    </div>
    <div class="col-md-6 align-self-center pt-1">
      <%=form_tag("/plans", method:"get", align:"center") do%>
      <%= select_tag(:selected_val, options_for_select(["内容","ハッシュタグ"], selected:params[:selected_val]), class:"plan-title")%>
      <%= text_field_tag :search, params[:search],class:"plan-title" %>
      <%= submit_tag "検索", :name => nil,class:"plan-title" %>
      <%end%>
    </div>
    <div class="col-md-3">
      <%= link_to image_tag("New_Plan.png", align:"right", class:"img-responsive", size:"300x135"), "/plans/new" %>
    </div>
  </div>
</div>



  <div class="container-fluid px-4">

    <div class="row py-4">
    <%if @plans.length == 0%>
    <div class="col-md-12 p-5">
      <p class="plan-title text-center">
        検索結果はありません
      </p>
    </div>
    <%end%>
      <div class=" card-deck-wrapper px-4">
        <div class="card-deck">
          <%= render(partial: "index", collection:@plans)%>
        </div>
      </div>
    </div>
  </div>

<% end %>

yuitama_app/app/views/plans/new.html.erb
<%= content_for(:maincontent)  do %>
<div class="container-fluid p-5">

<%= render partial:'form', locals:{plan: @plan} %>

<%= link_to 'Back', plans_path %>
<% end %>
</div>

yuitama_app/app/views/plans/show.html.erb
<%= content_for(:maincontent)  do %>
<div class="container-fluid p-5">
  <p id="notice"><%= notice %></p>

  <%= render(partial:"show", locals:{plan:@plan})%>


  <div class="pt-5">
  <%= render(partial: "/comments/index", collection:@comments)%>
  <%= render(partial: "/comments/form", locals:{plan_id: @plan.id})%>
  </div>


</div>




<% end %>