yuitama_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :plans
  resources :plans do
	member do
	  get 'show_image'
	end
  end
  resources :comments
  post "/utinaantyu/login" => "utinaantyus#login"
  get "/utinaantyus/login" => "utinaantyus#login_form"
  get "/utinaantyus/logout" =>"utinaantyus#logout"
  get '/plans/:id/book' => 'plans#book'
  get '/users/:user_id/:plan_id/cansel' => 'plans#cansel'
  get 'accept_plan/planMylist'
  get 'accept_plan/planDetail'
  get 'accept_plan/planList'

  get 'plan_consul/consensus'

  get 'provide_plan/planInput'
  get 'provide_plan/regiComp'
  get 'provide_plan/myPlanList'

  resources :users
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get "/user/signup" => "users#new"
  post "users/create" => "users#create"
  get "users/:id/edit" => "users#edit"
  post "users/:id/update" => "users#update"

  get "users/:id/mypage" => "users#mypage"
  get "/user/login" => "users#loginuser"
  post "/user/login" => "users#loginpost"
  get "/user/logout" => "users#logoutuser"


  resources :utinaantyus
  root 'home#index'
  # ホーム画面
  get 'home/index'
  # プランホーム画面
  get 'home/planHome'
  # ホームからログイン画面
  get 'home/login'

  # 個人情報登録画面
  get 'personal_info/input'
  # 個人情報登録完了画面
  get 'personal_info/regiComp'
  # ウチナーンチュマイページ
  get 'personal_info/mypage'
  # ウチナーンチュプロフィール編集
  get 'personal_info/editProf'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yuitama_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action:forbid_login_user,{only:[:]}
  def index
    @plans = Plan.all.first(6)
  end

  def transPersonal
  end

  def planHome
	redirect_to "/plans"
  end
end

yuitama_app/app/views/home/index.html.erb
<%= content_for(:maincontent)  do %>

<div class="container-fluid p-5">
  <!-- Example row of columns -->
  <div class="row px-5">
      <div class="alert alert-info" role="alert">
        <h2 class="plan-title">プランを探す</h2>
        <p class="plan-content ext-dark py-5">あなた様が気になる<strong>カテゴリ</strong>をクリックして、<strong>お気に入りのプラン</strong>を見つけましょう。<br>ここに表示されているカテゴリ以外にも様々なカテゴリのプランをご用意しております。</p>
        <div class="container-fluid">
          <div class=" card-deck-wrapper">
            <div class="card-deck">
              <div class="col-md-4 py-4">
                <div class="card">
                  <img class="card-img-top" src="https://www.photock.jp/photo/middle/photo0000-1642.jpg" alt="Card image cap">
                  <div class="card-body">
                    <h4 class="card-title">観光地</h4>
                    <p class="card-text">沖縄には歴史的な建造物や、風情ある観光名所がたくさんあります。
                      是非一度訪れてみてはいかがでしょうか？</p>
                      <div class="py-2">
                        <%= link_to("観光地のプラン一覧", plans_path(search: "観光地", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg plan-title", style:"font-size:1.5vw;")%>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 py-4">
                  <div class="card">
                    <img class="card-img-top" src="https://www.photock.jp/photo/middle/photo0000-1984.jpg" alt="Card image cap">
                    <div class="card-body">
                      <h4 class="card-title">自然</h4>
                      <p class="card-text">綺麗な海や車で行ける小さな離島など、沖縄は豊かな自然で溢れています。
                        リフレッシュをしたい方にオススメのプランをご用意しております。
                        <div class="py-2">
                          <%= link_to("自然のプラン一覧", plans_path(search: "自然", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg plan-title", style:"font-size:1.5vw;")%>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-md-4 p-4">
                    <div class="card">
                      <img class="card-img-top" src="https://d1f5hsy4d47upe.cloudfront.net/79/798ccb9c0c1e8e7589b778e9a0eeae1c_t.jpeg" alt="Card image cap">
                      <div class="card-body">
                        <h4 class="card-title">グルメ</h4>
                        <p class="card-text">現地のコンシェルジュたちがオススメする
                          様々な沖縄料理を楽しめるプランを多数ご用意しております。
                          <div class="py-2">
                            <%= link_to("グルメのプラン一覧", plans_path(search: "グルメ", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg py-2 plan-title", style:"font-size:1.5vw;")%>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4 p-4">
                      <div class="card">
                        <%= image_tag "denkyu_soda.jpg" ,class:"card-img-top"%>
                        <div class="card-body">
                          <h4 class="card-title">ジェニスポ</h4>
                          <p class="card-text">
                            インスタ映えのするフォトジェニックなスポット、その名もジェニスポ！フォトジェニックとは「写真写りの良い」という意味。
                            インスタ映えするような写真がたくさん撮れること間違いなし！
                          </p>
                            <div class="py-2">
                              <%= link_to("ジェニスポのプラン一覧", plans_path(search: "ジェニスポ", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg plan-title", style:"font-size:1.5vw;")%>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-4 p-4">
                        <div class="card">
                          <img class="card-img-top" src="https://www.photock.jp/photo/middle/photo0000-1975.jpg" alt="Card image cap">
                          <div class="card-body">
                            <h4 class="card-title">体験</h4>
                            <p class="card-text">
                              体験型ツアー！沖縄の昔の暮らしなど実際に体験してみませんか？体を動かしながらの体験はSo Exciting!!
                            </p>
                              <div class="py-2">
                                <%= link_to("体験のプラン一覧", plans_path(search: "体験", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg plan-title", style:"font-size:1.5vw;")%>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-4 p-4">
                          <div class="card">
                            <%= image_tag "habusyu.jpg" ,class:"card-img-top"%>
                            <div class="card-body">
                              <h4 class="card-title">買い物</h4>
                              <p class="card-text">
                                沖縄でしか買えないお買い物を提供します。伝統工芸品から沖縄の人しか知らないマニアな一品まで。
                              </p>
                                <div class="py-2">
                                  <%= link_to("買い物のプラン一覧", plans_path(search: "買い物", selected_val: "ハッシュタグ"), class:"btn btn-primary btn-lg plan-title", style:"font-size:1.5vw;")%>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>

              <div class="row px-5 pt-5">
                  <div class="alert alert-success" role="alert">
                    <h2 class="plan-title">プラン</h2>
                    <div class=" card-deck-wrapper">
                      <div class="card-deck">
                        <%= render(partial: "plans/index", collection:@plans)%>
                      </div>
                    </div>
                    <div class="py-4">
                      <%= link_to("もっと見る", plans_path(), class:"btn btn-primary btn-lg plan-title col-md-12", style:"font-size:1.5vw;")%>
                    </div>
                  </div>


              </div>
            </div>
<% end %>

yuitama_app/app/views/home/login.html.erb
<%= content_for(:maincontent)  do %>

<div class="container-fluid p-5 justify-content-center">
  <div class="col-md-offset-3 col-md-6">
    <div class="card">
      <div class="card-body">

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
    <p class="plan-content">各種ログイン</p>
      </div>
  </div>
  <div class="row py-4 justify-content-center">
    <div class="col-md-6">
      <%= link_to image_tag("Utinaantyus-Login.png", class:"img-responsive img-thumbnail", size:"500x150"), "/utinaantyus/login" %>
    </div>
  </div>
  <div class="row py-4 justify-content-center">
    <div class="col-md-6">
      <%= link_to image_tag("Traveler-Login.png", class:"img-responsive img-thumbnail", size:"500x150"), "/user/login" %>
    </div>
  </div>

  <div class="row pt-5">
    <div class="col-md-offset-3 col-md-6">
    <p class="plan-content">各種 新規登録</p>
      </div>
  </div>

  <div class="row py-4 justify-content-center">
    <div class="col-md-6">
      <%= link_to image_tag("Utinaantyus-NewRegistration.png", class:"img-responsive img-thumbnail", size:"500x150"), "/utinaantyus/new" %>
    </div>
  </div>
  <div class="row py-4 justify-content-center">
    <div class="col-md-6">
      <%= link_to image_tag("Traveler-NewRegistration.png", class:"img-responsive img-thumbnail", size:"500x150"), new_user_path %>
    </div>
  </div>

      </div>
      </div>
    </div>
</div>

<% end %>

<!-- <%= button_to "homeへ戻る", {:controller => 'home', :action => 'index'}, :method => :get %>
<%= button_to "登録", {:controller => 'personal_info', :action => 'regiComp'}, :method => :get %> -->

yuitama_app/app/views/home/planHome.html.erb
<%= content_for(:maincontent)  do %>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
      <div class="col-md-4">
		<h1>プラン一覧</h1>
       </div>
      </div>

    <table class="table table-hover">
      <tr><th>プラン名</th><th>うちなーんちゅ名</th><th>登録日</th></tr>
      <tr><td>観光名所をたくさんまわろう！</td><td>山田</td><td>2017/12/20</td></tr>
      <tr><td>美ら海を堪能しよう！</td><td>鈴木</td><td>2017/12/11</td></tr>
      <tr><td>美味しい食べ物知ってます</td><td>グルメに自信ある</td><td>1990/02/23</td></tr>
    </table>
      <hr>
<% end %>