yuitama_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :plans
  resources :plans do
	member do
	  get 'show_image'
	end
  end
  resources :comments
  post "/utinaantyu/login" => "utinaantyus#login"
  get "/utinaantyus/login" => "utinaantyus#login_form"
  get "/utinaantyus/logout" =>"utinaantyus#logout"
  get '/plans/:id/book' => 'plans#book'
  get '/users/:user_id/:plan_id/cansel' => 'plans#cansel'
  get 'accept_plan/planMylist'
  get 'accept_plan/planDetail'
  get 'accept_plan/planList'

  get 'plan_consul/consensus'

  get 'provide_plan/planInput'
  get 'provide_plan/regiComp'
  get 'provide_plan/myPlanList'

  resources :users
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get "/user/signup" => "users#new"
  post "users/create" => "users#create"
  get "users/:id/edit" => "users#edit"
  post "users/:id/update" => "users#update"

  get "users/:id/mypage" => "users#mypage"
  get "/user/login" => "users#loginuser"
  post "/user/login" => "users#loginpost"
  get "/user/logout" => "users#logoutuser"


  resources :utinaantyus
  root 'home#index'
  # ホーム画面
  get 'home/index'
  # プランホーム画面
  get 'home/planHome'
  # ホームからログイン画面
  get 'home/login'

  # 個人情報登録画面
  get 'personal_info/input'
  # 個人情報登録完了画面
  get 'personal_info/regiComp'
  # ウチナーンチュマイページ
  get 'personal_info/mypage'
  # ウチナーンチュプロフィール編集
  get 'personal_info/editProf'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yuitama_app/app/models/utinaantyu.rb
class Utinaantyu < ApplicationRecord
  validates :password, {presence: true}
  has_one :profile, dependent: :destroy, foreign_key:"id"
end

yuitama_app/app/controllers/utinaantyus_controller.rb
class UtinaantyusController < ApplicationController
  before_action :set_utinaantyu, only: [:show, :edit, :update, :destroy]
  before_action :set_currentuser
  before_action :authenticate_user, only: [:edit, :update]
  before_action :forbid_login_user, only: [:login, :new, :create, :login_form]
  before_action :ensure_correct_user, only: [:edit, :update]

  # GET /utinaantyus
  # GET /utinaantyus.json
  def index
    @utinaantyus = Utinaantyu.all
  end

  # GET /utinaantyus/1
  # GET /utinaantyus/1.json
  def show
    @counter = 0
  end

  # GET /utinaantyus/new
  def new
    @utinaantyu = Utinaantyu.new
  end

  # GET /utinaantyus/1/edit
  def edit
  end

  # POST /utinaantyus
  # POST /utinaantyus.json
  def create
    @utinaantyu = Utinaantyu.new(utinaantyu_params)

    respond_to do |format|
      if @utinaantyu.save
        session[:user_id] = @utinaantyu.id
        format.html { redirect_to @utinaantyu, notice: 'Utinaantyu was successfully created.' }
        format.json { render :show, status: :created, location: @utinaantyu }
      else
        format.html { render :new }
        format.json { render json: @utinaantyu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utinaantyus/1
  # PATCH/PUT /utinaantyus/1.json
  def update
    @utinaantyu = Utinaantyu.find(params[:id])
    respond_to do |format|
      if @utinaantyu.update(utinaantyu_params)
        format.html { redirect_to @utinaantyu, notice: 'Utinaantyu was successfully updated.' }
        format.json { render :show, status: :ok, location: @utinaantyu }
      else
        format.html { render :edit }
        format.json { render json: @utinaantyu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utinaantyus/1
  # DELETE /utinaantyus/1.json
  def destroy
    @utinaantyu.destroy
    respond_to do |format|
      format.html { redirect_to utinaantyus_url, notice: 'Utinaantyu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    @utinaantyu = Utinaantyu.find_by(mailaddress: params[:mailaddress],password: params[:password])
    if @utinaantyu
      session[:user_id] = @utinaantyu.id
      session[:pub_user_id] = nil #旅行者垢はログアウト
      flash[:notice] ="#{@utinaantyu.name}さんがログインしました。"
      redirect_to("/")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています。"
      render("/utinaantyus/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice]="ログアウトしました。"
    redirect_to("/home/login")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utinaantyu
      @utinaantyu = Utinaantyu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utinaantyu_params
      params.require(:utinaantyu).permit(:name, :age, :mailaddress, :password, :introduction)
    end

    def set_currentuser
      @current_utinaantyu = Utinaantyu.find_by(id: session[:user_id])
    end

    def authenticate_user
      if @current_utinaantyu == nil
        flash[:notice] = "ログインが必要です"
        redirect_to("/utinaantyus/login")
      end
    end

    def forbid_login_user
      if @current_utinaantyu
        flash[:notice] = "すでにログインしています"
        redirect_to("/plans")
      end
    end

    def ensure_correct_user
      if @current_utinaantyu == params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to("/plans")
      end
    end
end

yuitama_app/app/helpers/utinaantyus_helper.rb
module UtinaantyusHelper
end

yuitama_app/app/views/utinaantyus/_form.html.erb
<%= content_for(:maincontent) do %>
<div class="container-fluid">
  <%= form_with(model: utinaantyu, local: true, class:"form-horizontal") do |form| %>
  <% if utinaantyu.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(utinaantyu.errors.count, "error") %> prohibited this utinaantyu from being saved:</h2>

    <ul>
      <% utinaantyu.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>



<div class="row py-4 justify-content-md-center">
  <div class="col-md-8">
    <div class="card">

      <div class="card-header">
        <div class="row pl-4">
          <h1 class="pt-1 plan-title text-left"><strong>プロフィール</strong></h1>
          <% if @current_utinaantyu != nil%>
          <%if @utinaantyu.id == @current_utinaantyu.id%>
          <div class="pt-2 pl-4">
            <%= link_to '編集', edit_utinaantyu_path(@utinaantyu), style:"font-size:1.5vw" %>
          </div>
          <%end%>
          <%end%>
        </div>
      </div>

      <div class="card-body p-5 ">
        <!-- ここに写真下側の文字 -->
        <!--<div class="align-self-center p-5 col-md-6">-->

        <div class="row py-2">
          <div class="col-md-3">
            <%= form.label "名前：", class:"control-label plan-content", style:"font-weight:bold"%>
          </div>
          <div class="col-md-9">
            <%= form.text_field :name, id: :utinaantyu_name ,:class => "form-control",style:"font-size:1.5vw;line-height:2.5vw;",size:"30x2"%>
          </div>
        </div>

        <div class="row py-2">
          <div class="col-md-3">
            <%= form.label "年齢：", class:"control-label plan-content", style:"font-weight:bold" %>
          </div>
          <div class="col-md-9">
            <%= form.number_field :age, id: :utinaantyu_age,:class => "form-control",style:"font-size:1.5vw" %>
          </div>
        </div>

        <div class="row py-2">
          <div class="col-md-3">
            <%= form.label "メールアドレス：", class:"control-label plan-content", style:"font-weight:bold" %>
          </div>
          <div class="col-md-9">
            <%= form.text_field :mailaddress, id: :utinaantyu_mailaddress,:class => "form-control",style:"font-size:1.5vw" %>
          </div>
        </div>

        <div class="row py-2">
          <div class="col-md-3">
            <%= form.label "パスワード：", class:"control-label plan-content", style:"font-weight:bold" %>
          </div>
          <div class="col-md-9">
            <%= form.text_field :password, id: :utinaantyu_password,:class => "form-control",style:"font-size:1.5vw" %>
          </div>
        </div>

        <div class="row py-2">
          <div class="col-md-3">
            <%= form.label "自己紹介：", class:"control-label plan-content", style:"font-weight:bold" %>
          </div>
          <div class="col-md-9">
            <%= form.text_area :introduction, id: :utinaantyu_mailaddress,:class => "form-control",size:"10x5",style:"font-size:1.5vw" %>
          </div>
        </div>

        <div class="row py-2">
            <div class="col-md-offset-3 col-md-9">
          <div class="actions">
              <%= form.submit class:"btn btn-primary btn-block",style:"font-size:1.5vw"%>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
</div>
<% end %>
<% end %>

yuitama_app/app/views/utinaantyus/_index.html.erb
<%= content_for(:maincontent) do %>
<p id="notice"><%= notice %></p>

<h1>Utinaantyus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Mailaddress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utinaantyus.each do |utinaantyu| %>
      <tr>
        <td><%= utinaantyu.name %></td>
        <td><%= utinaantyu.age %></td>
        <td><%= utinaantyu.mailaddress %></td>
        <td><%= link_to 'Show', utinaantyu %></td>
        <td><%= link_to 'Edit', edit_utinaantyu_path(utinaantyu) %></td>
        <td><%= link_to 'Destroy', utinaantyu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utinaantyu', new_utinaantyu_path %>
<%end%>

yuitama_app/app/views/utinaantyus/edit.html.erb
<h1>Editing Utinaantyu</h1>

<%= render 'form', utinaantyu: @utinaantyu %>

<%= link_to 'Show', @utinaantyu %> |
<%= link_to 'Back', utinaantyus_path %>

yuitama_app/app/views/utinaantyus/index.html.erb
<%= content_for(:maincontent) do %>
<p id="notice"><%= notice %></p>

<h1>Utinaantyus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Mailaddress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utinaantyus.each do |utinaantyu| %>
      <tr>
        <td><%= utinaantyu.name %></td>
        <td><%= utinaantyu.age %></td>
        <td><%= utinaantyu.mailaddress %></td>
        <td><%= link_to 'Show', utinaantyu %></td>
        <td><%= link_to 'Edit', edit_utinaantyu_path(utinaantyu) %></td>
        <td><%= link_to 'Destroy', utinaantyu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utinaantyu', new_utinaantyu_path %>
<%end%>

yuitama_app/app/views/utinaantyus/login_form.html.erb
<%= content_for(:maincontent) do %>

<div class="container-fluid p-5 ">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="card">
          <div class="card-header p-4">
            <p class="plan-title">ウチナーンチュログイン</p>
            </div>
          <div class="card-body">
            <div class="card-text">


<%= form_tag(utinaantyu_login_path, class:"form-horizontal") do |form| %>
  <div id="form-error">
    <%= @error_message %>
  </div>

  <div class="form-group">
    <div class="col-md-3">
      <%= label_tag :mailaddress, "メールアドレス", class:"form-content"%>
    </div>
    <div class=" col-md-9">
      <%= text_field_tag :mailaddress, params[:mailaddress] , class:"form-content"%>
    </div>
  </div>

  <div class="form-group">
    <div class=" col-md-3">
      <%= label_tag :password, "パスワード" , class:"form-content"%>
    </div>
    <div class=" col-md-9">
      <%= password_field_tag :password, params[:password] , class:"form-content"%>
    </div>
  </div>

  <div class="actions">
    <div class=" col-md-offset-2 col-md-10 pt-4">
      <%= submit_tag "ログイン", class:"form-content"%>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>
  <% end %>
<% end %>

yuitama_app/app/views/utinaantyus/new.html.erb
<%= content_for(:maincontent) do %>
<h1>New Utinaantyu</h1>

<%= render 'form', utinaantyu: @utinaantyu %>

<%= link_to 'Back', utinaantyus_path %>
<% end %>

yuitama_app/app/views/utinaantyus/show.html.erb
<%= content_for(:maincontent) do %>
<%if notice != nil%>
<p id="notice"><%= notice %></p>
<%end%>

<div class="row py-4 justify-content-md-center">
  <div class="col-md-8">
    <div class="card">

      <div class="card-header">
        <div class="row pl-4">
        <h1 class="pt-1 plan-title text-left"><strong>プロフィール</strong></h1>
        <% if @current_utinaantyu != nil%>
          <%if @utinaantyu.id == @current_utinaantyu.id%>
            <div class="pt-2 pl-4">
            <%= link_to '編集', edit_utinaantyu_path(@utinaantyu), style:"font-size:1.5vw" %>
            </div>
          <%end%>
        <%end%>
        </div>
      </div>

      <div class="card-body p-5 ">
      <!-- ここに写真下側の文字 -->
      <!--<div class="align-self-center p-5 col-md-6">-->

        <div class="row">
          <div class="col-md-3">
            <p class="plan-content"><strong>名前：</strong></p>
          </div>
          <div class="col-md-9">
            <p class="pb-5 plan-content"><%= @utinaantyu.name %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <p class="plan-content"><strong>年齢：</strong></p>
          </div>
          <div class="col-md-9">
            <p class="pb-5 plan-content"><%=@utinaantyu.age%></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <p class="plan-content"><strong>メールアドレス：</strong></p>
          </div>
          <div class="col-md-9">
            <p class="pb-5 plan-content"><%= @utinaantyu.mailaddress %></p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">
            <p class="plan-content"><strong>自己紹介：</strong></p>
          </div>
          <div class="col-md-9">
            <p class="pb-5 plan-content"><%= @utinaantyu.introduction %></p>
          </div>
        </div>
    </div>
  </div>
</div>
</div>

<div class="row py-4 justify-content-md-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body p-5 ">
<h2 class="plan-title">この方のプラン</h2>
<% @plans = Plan.where(creator_id: @utinaantyu.id) %>
<div class=" card-deck-wrapper px-4">
  <div class="card-deck">
    <%= render :partial => "plans/index", collection:@plans %>
  </div>
</div>
  </div>
  </div>
</div>
</div>



<% end %>